jobs:
  - job: UiAutomator2ServerCI
    pool:
      vmImage: macOS-10.13
    variables:
      CI: true
      TERM: dumb
      ANDROID_SDK_VERSION: 28
      ANDROID_AVD: test
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - script: npm install
      displayName: Install Node dependencies
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: ./gradlew clean connectedE2ETestDebugAndroidTest
      displayName: Run Gradle Tests