jobs:
  - job: UiAutomator2CI
    pool:
      vmImage: macOS-10.13
    variables:
      CI: true
      TERM: dumb
    steps:
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: ./gradlew clean connectedE2ETestDebugAndroidTest
      displayName: Run Gradle Tests